spring:
  jpa:
    show-sql: true
    database-platform:
      org:
        hibernate:
          dialect: MySQL5InnoDBDialect

  datasource:
    name: MySQL Database
    url: jdbc:mysql://localhost:3306/logate_akademija_2023
    username: root
    password: Password1.2.3.
    driver-class-name: com.mysql.cj.jdbc.Driver


twitter-api:
  url: 192.168.42.45/api/twitter
  user-name: userDev
  port: 889
  token: password222


external-post-api:
  url: "https://jsonplaceholder.typicode.com/posts"

external-fake-store-api:
  url: "https://fakestoreapi.com/products"